ProxyRequests Off
ProxyPreserveHost On

<Proxy "balancer://backendcluster">
    BalancerMember "http://10.0.0.153:5000" route=server1
    BalancerMember "http://10.0.0.196:5000" route=server2

    ProxySet lbmethod=byrequests
</Proxy>

ProxyPass "/api/" "balancer://backendcluster/"
ProxyPassReverse "/api/" "balancer://backendcluster/"

ProxyPass "/static/" "balancer://backendcluster/static/"
ProxyPassReverse "/static/" "balancer://backendcluster/static/"